"""add proejct_competence_id to ProjectRequirement

Revision ID: b83dd3a01a7c
Revises: 
Create Date: 2025-07-20 13:13:21.991700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83dd3a01a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_competence_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'competence', ['project_competence_id'], ['id'])
        batch_op.drop_column('project_competence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_competence', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_competence_id')

    # ### end Alembic commands ###
